[2024-07-01T12:11:38.489+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-01T12:11:38.568+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: purchase_dag.kafka_topic_creation manual__2024-07-01T12:11:37.556381+00:00 [queued]>
[2024-07-01T12:11:38.584+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: purchase_dag.kafka_topic_creation manual__2024-07-01T12:11:37.556381+00:00 [queued]>
[2024-07-01T12:11:38.585+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-01T12:11:38.614+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): kafka_topic_creation> on 2024-07-01 12:11:37.556381+00:00
[2024-07-01T12:11:38.626+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=385) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-01T12:11:38.628+0000] {standard_task_runner.py:63} INFO - Started process 387 to run task
[2024-07-01T12:11:38.633+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'purchase_dag', 'kafka_topic_creation', 'manual__2024-07-01T12:11:37.556381+00:00', '--job-id', '469', '--raw', '--subdir', 'DAGS_FOLDER/purchase_dag.py', '--cfg-path', '/tmp/tmpzgouh0ty']
[2024-07-01T12:11:38.637+0000] {standard_task_runner.py:91} INFO - Job 469: Subtask kafka_topic_creation
[2024-07-01T12:11:38.663+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-07-01T12:11:38.744+0000] {task_command.py:426} INFO - Running <TaskInstance: purchase_dag.kafka_topic_creation manual__2024-07-01T12:11:37.556381+00:00 [running]> on host 6d5f7889ee5a
[2024-07-01T12:11:38.934+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='purchase_dag' AIRFLOW_CTX_TASK_ID='kafka_topic_creation' AIRFLOW_CTX_EXECUTION_DATE='2024-07-01T12:11:37.556381+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-01T12:11:37.556381+00:00'
[2024-07-01T12:11:38.935+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-01T12:11:38.960+0000] {conn.py:380} INFO - <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2024-07-01T12:11:38.960+0000] {conn.py:1206} INFO - Probing node bootstrap-0 broker version
[2024-07-01T12:11:38.961+0000] {conn.py:418} ERROR - Connect attempt to <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]> returned error 111. Disconnecting.
[2024-07-01T12:11:38.962+0000] {conn.py:919} INFO - <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-07-01T12:11:39.009+0000] {conn.py:380} INFO - <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2024-07-01T12:11:39.010+0000] {conn.py:418} ERROR - Connect attempt to <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]> returned error 111. Disconnecting.
[2024-07-01T12:11:39.010+0000] {conn.py:919} INFO - <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-07-01T12:11:39.059+0000] {conn.py:380} INFO - <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2024-07-01T12:11:39.060+0000] {conn.py:418} ERROR - Connect attempt to <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]> returned error 111. Disconnecting.
[2024-07-01T12:11:39.060+0000] {conn.py:919} INFO - <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-07-01T12:11:39.061+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-01T12:11:39.061+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/script_kafka.py", line 12, in kafka_topic_creation
    create_kafka_topic(broker, topic_name, num_partitions, replication_factor)
  File "/opt/airflow/dags/script_kafka.py", line 17, in create_kafka_topic
    admin_client = KafkaAdminClient(
                   ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/kafka/admin/client.py", line 210, in __init__
    self._client = self.config['kafka_client'](
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py", line 244, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py", line 900, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2024-07-01T12:11:39.079+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=purchase_dag, task_id=kafka_topic_creation, run_id=manual__2024-07-01T12:11:37.556381+00:00, execution_date=20240701T121137, start_date=20240701T121138, end_date=20240701T121139
[2024-07-01T12:11:39.135+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 469 for task kafka_topic_creation (NoBrokersAvailable; 387)
[2024-07-01T12:11:39.182+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-01T12:11:39.254+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-01T12:11:39.257+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
