[2024-06-24T18:59:00.199+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-24T18:59:00.245+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Stage_1.kafka_producer manual__2024-06-24T18:58:58.192624+00:00 [queued]>
[2024-06-24T18:59:00.259+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Stage_1.kafka_producer manual__2024-06-24T18:58:58.192624+00:00 [queued]>
[2024-06-24T18:59:00.260+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-24T18:59:00.278+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): kafka_producer> on 2024-06-24 18:58:58.192624+00:00
[2024-06-24T18:59:00.290+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=172) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-24T18:59:00.291+0000] {standard_task_runner.py:63} INFO - Started process 173 to run task
[2024-06-24T18:59:00.289+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Stage_1', 'kafka_producer', 'manual__2024-06-24T18:58:58.192624+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/kafka_dag.py', '--cfg-path', '/tmp/tmpnrr2hwku']
[2024-06-24T18:59:00.293+0000] {standard_task_runner.py:91} INFO - Job 32: Subtask kafka_producer
[2024-06-24T18:59:00.311+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-06-24T18:59:00.366+0000] {task_command.py:426} INFO - Running <TaskInstance: Stage_1.kafka_producer manual__2024-06-24T18:58:58.192624+00:00 [running]> on host b52dbab8fc24
[2024-06-24T18:59:00.504+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Stage_1' AIRFLOW_CTX_TASK_ID='kafka_producer' AIRFLOW_CTX_EXECUTION_DATE='2024-06-24T18:58:58.192624+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-24T18:58:58.192624+00:00'
[2024-06-24T18:59:00.505+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-24T18:59:00.522+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-24T18:59:00.523+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/kafka_scripts.py", line 17, in kafka_producer_script
    with open(data_path, 'r') as file:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/src/purchases.json'
[2024-06-24T18:59:00.534+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Stage_1, task_id=kafka_producer, run_id=manual__2024-06-24T18:58:58.192624+00:00, execution_date=20240624T185858, start_date=20240624T185900, end_date=20240624T185900
[2024-06-24T18:59:00.548+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 32 for task kafka_producer ([Errno 2] No such file or directory: '/opt/airflow/src/purchases.json'; 173)
[2024-06-24T18:59:00.591+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-24T18:59:00.615+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-24T18:59:00.617+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
