[2024-06-24T13:36:46.604+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-24T13:36:46.688+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: use_PythonOperator.kafka_create_topic manual__2024-06-24T13:36:45.770208+00:00 [queued]>
[2024-06-24T13:36:46.706+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: use_PythonOperator.kafka_create_topic manual__2024-06-24T13:36:45.770208+00:00 [queued]>
[2024-06-24T13:36:46.707+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-24T13:36:46.733+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): kafka_create_topic> on 2024-06-24 13:36:45.770208+00:00
[2024-06-24T13:36:46.742+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=252) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-24T13:36:46.743+0000] {standard_task_runner.py:63} INFO - Started process 253 to run task
[2024-06-24T13:36:46.743+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'use_PythonOperator', 'kafka_create_topic', 'manual__2024-06-24T13:36:45.770208+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/kafka_dag.py', '--cfg-path', '/tmp/tmp3lfduc_8']
[2024-06-24T13:36:46.746+0000] {standard_task_runner.py:91} INFO - Job 7: Subtask kafka_create_topic
[2024-06-24T13:36:46.764+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-06-24T13:36:46.819+0000] {task_command.py:426} INFO - Running <TaskInstance: use_PythonOperator.kafka_create_topic manual__2024-06-24T13:36:45.770208+00:00 [running]> on host 8e89500c3118
[2024-06-24T13:36:46.938+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='use_PythonOperator' AIRFLOW_CTX_TASK_ID='kafka_create_topic' AIRFLOW_CTX_EXECUTION_DATE='2024-06-24T13:36:45.770208+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-24T13:36:45.770208+00:00'
[2024-06-24T13:36:46.939+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-24T13:36:46.962+0000] {conn.py:380} INFO - <BrokerConnection node_id=bootstrap-0 host=localhost:9094 <connecting> [IPv6 ('::1', 9094, 0, 0)]>: connecting to localhost:9094 [('::1', 9094, 0, 0) IPv6]
[2024-06-24T13:36:46.963+0000] {conn.py:1206} INFO - Probing node bootstrap-0 broker version
[2024-06-24T13:36:46.964+0000] {conn.py:418} ERROR - Connect attempt to <BrokerConnection node_id=bootstrap-0 host=localhost:9094 <connecting> [IPv6 ('::1', 9094, 0, 0)]> returned error 111. Disconnecting.
[2024-06-24T13:36:46.964+0000] {conn.py:919} INFO - <BrokerConnection node_id=bootstrap-0 host=localhost:9094 <connecting> [IPv6 ('::1', 9094, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-06-24T13:36:47.012+0000] {conn.py:380} INFO - <BrokerConnection node_id=bootstrap-0 host=localhost:9094 <connecting> [IPv6 ('::1', 9094, 0, 0)]>: connecting to localhost:9094 [('::1', 9094, 0, 0) IPv6]
[2024-06-24T13:36:47.013+0000] {conn.py:418} ERROR - Connect attempt to <BrokerConnection node_id=bootstrap-0 host=localhost:9094 <connecting> [IPv6 ('::1', 9094, 0, 0)]> returned error 111. Disconnecting.
[2024-06-24T13:36:47.013+0000] {conn.py:919} INFO - <BrokerConnection node_id=bootstrap-0 host=localhost:9094 <connecting> [IPv6 ('::1', 9094, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-06-24T13:36:47.062+0000] {conn.py:380} INFO - <BrokerConnection node_id=bootstrap-0 host=localhost:9094 <connecting> [IPv4 ('127.0.0.1', 9094)]>: connecting to localhost:9094 [('127.0.0.1', 9094) IPv4]
[2024-06-24T13:36:47.063+0000] {conn.py:418} ERROR - Connect attempt to <BrokerConnection node_id=bootstrap-0 host=localhost:9094 <connecting> [IPv4 ('127.0.0.1', 9094)]> returned error 111. Disconnecting.
[2024-06-24T13:36:47.063+0000] {conn.py:919} INFO - <BrokerConnection node_id=bootstrap-0 host=localhost:9094 <connecting> [IPv4 ('127.0.0.1', 9094)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-06-24T13:36:47.063+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-24T13:36:47.064+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/kafka_create_topic.py", line 14, in create_kafka_topic
    admin_client = KafkaAdminClient(bootstrap_servers=bootstrap_servers, client_id='kafka-python-example')
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/kafka/admin/client.py", line 210, in __init__
    self._client = self.config['kafka_client'](
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py", line 244, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py", line 900, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2024-06-24T13:36:47.077+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=use_PythonOperator, task_id=kafka_create_topic, run_id=manual__2024-06-24T13:36:45.770208+00:00, execution_date=20240624T133645, start_date=20240624T133646, end_date=20240624T133647
[2024-06-24T13:36:47.095+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 7 for task kafka_create_topic (NoBrokersAvailable; 253)
[2024-06-24T13:36:47.122+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-24T13:36:47.146+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-24T13:36:47.149+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
