[2024-06-26T18:51:45.667+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-26T18:51:45.709+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Stage_1.run_bronze_job manual__2024-06-26T18:51:39.373786+00:00 [queued]>
[2024-06-26T18:51:45.720+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Stage_1.run_bronze_job manual__2024-06-26T18:51:39.373786+00:00 [queued]>
[2024-06-26T18:51:45.721+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-26T18:51:45.738+0000] {taskinstance.py:2330} INFO - Executing <Task(DockerOperator): run_bronze_job> on 2024-06-26 18:51:39.373786+00:00
[2024-06-26T18:51:45.746+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=179) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-26T18:51:45.747+0000] {standard_task_runner.py:63} INFO - Started process 180 to run task
[2024-06-26T18:51:45.746+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Stage_1', 'run_bronze_job', 'manual__2024-06-26T18:51:39.373786+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/kafka_dag.py', '--cfg-path', '/tmp/tmpm5elrnnf']
[2024-06-26T18:51:45.748+0000] {standard_task_runner.py:91} INFO - Job 18: Subtask run_bronze_job
[2024-06-26T18:51:45.763+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-06-26T18:51:45.799+0000] {task_command.py:426} INFO - Running <TaskInstance: Stage_1.run_bronze_job manual__2024-06-26T18:51:39.373786+00:00 [running]> on host 09fe08554062
[2024-06-26T18:51:45.895+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Stage_1' AIRFLOW_CTX_TASK_ID='run_bronze_job' AIRFLOW_CTX_EXECUTION_DATE='2024-06-26T18:51:39.373786+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-26T18:51:39.373786+00:00'
[2024-06-26T18:51:45.896+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-26T18:51:45.935+0000] {docker.py:493} INFO - Pulling docker image bitnami/spark:latest
[2024-06-26T18:51:46.965+0000] {docker.py:507} INFO - latest: Pulling from bitnami/spark
[2024-06-26T18:51:47.010+0000] {docker.py:507} INFO - 6d10d4f6c38d: Pulling fs layer
[2024-06-26T18:51:47.514+0000] {docker.py:507} INFO - 6d10d4f6c38d: Downloading
[2024-06-26T18:59:38.119+0000] {docker.py:507} INFO - 6d10d4f6c38d: Retrying in 5 seconds
[2024-06-26T18:59:39.119+0000] {docker.py:507} INFO - 6d10d4f6c38d: Retrying in 4 seconds
[2024-06-26T18:59:40.119+0000] {docker.py:507} INFO - 6d10d4f6c38d: Retrying in 3 seconds
[2024-06-26T18:59:41.119+0000] {docker.py:507} INFO - 6d10d4f6c38d: Retrying in 2 seconds
[2024-06-26T18:59:42.119+0000] {docker.py:507} INFO - 6d10d4f6c38d: Retrying in 1 second
[2024-06-26T18:59:44.070+0000] {docker.py:507} INFO - 6d10d4f6c38d: Downloading
[2024-06-26T19:03:23.280+0000] {local_task_job_runner.py:310} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-06-26T19:03:23.281+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-26T19:03:23.286+0000] {process_utils.py:132} INFO - Sending 15 to group 180. PIDs of all processes in the group: [180]
[2024-06-26T19:03:23.286+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 180
[2024-06-26T19:03:23.287+0000] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-06-26T19:03:23.287+0000] {docker.py:528} INFO - Stopping docker container
[2024-06-26T19:03:23.287+0000] {docker.py:530} INFO - Not attempting to kill container as it was not created
[2024-06-26T19:03:23.288+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-26T19:03:23.347+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=180, status='terminated', exitcode=0, started='18:51:44') (180) terminated with exit code 0
