[2024-06-24T17:59:49.007+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-24T17:59:49.074+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Stage_1.kafka_producer manual__2024-06-24T17:59:48.315007+00:00 [queued]>
[2024-06-24T17:59:49.092+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Stage_1.kafka_producer manual__2024-06-24T17:59:48.315007+00:00 [queued]>
[2024-06-24T17:59:49.093+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-24T17:59:49.120+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): kafka_producer> on 2024-06-24 17:59:48.315007+00:00
[2024-06-24T17:59:49.133+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Stage_1', 'kafka_producer', 'manual__2024-06-24T17:59:48.315007+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/kafka_dag.py', '--cfg-path', '/tmp/tmpqdfcgqus']
[2024-06-24T17:59:49.135+0000] {standard_task_runner.py:91} INFO - Job 13: Subtask kafka_producer
[2024-06-24T17:59:49.137+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=367) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-24T17:59:49.141+0000] {standard_task_runner.py:63} INFO - Started process 368 to run task
[2024-06-24T17:59:49.166+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-06-24T17:59:49.235+0000] {task_command.py:426} INFO - Running <TaskInstance: Stage_1.kafka_producer manual__2024-06-24T17:59:48.315007+00:00 [running]> on host 505254ae63d4
[2024-06-24T17:59:49.420+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Stage_1' AIRFLOW_CTX_TASK_ID='kafka_producer' AIRFLOW_CTX_EXECUTION_DATE='2024-06-24T17:59:48.315007+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-24T17:59:48.315007+00:00'
[2024-06-24T17:59:49.421+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-24T17:59:49.438+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-24T17:59:49.438+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/kafka_scripts.py", line 14, in kafka_producer_script
    admin_client = KafkaAdminClient(bootstrap_servers="localhost:9094", client_id='kafka-python-example')
                   ^^^^^^^^^^^^^^^^
NameError: name 'KafkaAdminClient' is not defined
[2024-06-24T17:59:49.455+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Stage_1, task_id=kafka_producer, run_id=manual__2024-06-24T17:59:48.315007+00:00, execution_date=20240624T175948, start_date=20240624T175949, end_date=20240624T175949
[2024-06-24T17:59:49.470+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 13 for task kafka_producer (name 'KafkaAdminClient' is not defined; 368)
[2024-06-24T17:59:49.481+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-24T17:59:49.508+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-24T17:59:49.515+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
